version: 2.1
jobs: 
  build: 
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  hithere:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run: echo "hello"
  deploy:
    docker:
      - image: cimg/node:17.5.0
    steps: 
      - checkout
      - run: echo "soft deploy"
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - hithere
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build